### ISSUE TITLE
[Bug] Parsing behaviors with concurrency takes extremely long when saved with spaces as indentation

### ISSUE THREAD

**Issue by achim-k** [pschillinger/flexbe_chrome_app#5]
The title basically says it all. If I save the same behavior with `tabs` as indentation, it works fine. I traced it down to https://github.com/pschillinger/flexbe_chrome_app/blob/b040351d91bf6a2aa21b5973f67ea5b1b9810eb6/FlexBE/src/_helper/codeparser.js#L277-L287. It takes ages there when the behavior was saved with `spaces` as indentation.
I assume that the regex patter `cc_definition_pattern` needs to be adapted? Bug was probably introduced by faea56748f1c63386c5bb11d438605e8cc8f80db ?

**Comment by pschillinger** [comment]
Thanks for pointing that out! The regex pattern actually contains a typo. It still matches the correct sequences, but this typo might cause the performance issue. I will fix it tomorrow, hope this resolves the issue.

**Comment by pschillinger** [comment]
I fixed the typo on the develop branch. Can you install [this version](https://github.com/pschillinger/flexbe_chrome_app/blob/develop/FlexBE.crx) and check if it also helps regarding the performance for you?

**Comment by achim-k** [comment]
It indeed fixed the performance issue. However, the regex pattern was still wrong, causing it to not recognize the whole ConcurrencyContainer element. Parts of it were instead parsed as private variable.
I created a PR #6 which should fix this issue.

**Comment by pschillinger** [comment]
Should be resolved by your fix. Feel free to close this issue if it works for you now.

**Comment by achim-k** [comment]
It did, thanks! Also for the `\s` hint
